---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: mydockerkey
    namespace: default
  data:
    .dockercfg: eyJkb2NrZXIuaW8iOnsicGFzc3dvcmQiOiJ0aGlzL2lzJWEjcGFzc3dvcmQiLCJlbWFpbCI6ImJhckBiYXIuY29tIiwidXNlcm5hbWUiOiJ1c2VybmFtZSJ9fQ==
  type: kubernetes.io/dockercfg
- apiVersion: v1
  kind: Secret
  metadata:
    name: mydockerkey1
    namespace: default
  data:
    .dockercfg: eyJkb2NrZXIxLmlvIjp7InBhc3N3b3JkIjoidGhpcy9pcyVhI3Bhc3N3b3JkITEiLCJlbWFpbCI6ImJhcjFAYmFyLmNvbSIsInVzZXJuYW1lIjoidXNlcm5hbWUxIn19
  type: kubernetes.io/dockercfg
- apiVersion: v1
  kind: Secret
  metadata:
    name: mydockerkey2
  data:
    .dockercfg: eyJkb2NrZXIxLmlvIjp7InBhc3N3b3JkIjoidGhpcy9pcyVhI3Bhc3N3b3JkITEiLCJlbWFpbCI6ImJhcjFAYmFyLmNvbSIsInVzZXJuYW1lIjoidXNlcm5hbWUxIn19
  type: kubernetes.io/dockercfg
